language: cpp
sudo: true
install: true
dist: focal

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: never

arch: amd64

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2

compiler:
  - gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt purge --auto-remove cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt upgrade -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y libsdl2-2.0-0 libsdl2-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then pip install cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="~/.local/bin:$PATH"; fi

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
  - cd build
  - make all